"""empty message

Revision ID: 2226184a5d7d
Revises: 3d51adbb381d
Create Date: 2020-06-02 09:22:45.885491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2226184a5d7d'
down_revision = '3d51adbb381d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('bvid', sa.String(length=20), nullable=True))
    op.add_column('post', sa.Column('stars', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('username', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'username')
    op.drop_column('post', 'stars')
    op.drop_column('post', 'bvid')
    # ### end Alembic commands ###
