"""empty message

Revision ID: dd2f73af810c
Revises: dfa7f6493c3d
Create Date: 2020-06-06 10:51:12.698774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd2f73af810c'
down_revision = 'dfa7f6493c3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('vid_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'vid_url')
    # ### end Alembic commands ###
