"""empty message

Revision ID: dfa7f6493c3d
Revises: 2226184a5d7d
Create Date: 2020-06-02 17:37:01.155819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfa7f6493c3d'
down_revision = '2226184a5d7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('aid', sa.String(length=20), nullable=True))
    op.add_column('post', sa.Column('cid', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'cid')
    op.drop_column('post', 'aid')
    # ### end Alembic commands ###
